local input_remote_tv = require "input.input_remote_tv.modules.input_remote_tv"

function init(self)
	pprint("self", on_input)
end

function final(self)
	
end

function update(self, dt)
	msg.post(".", "acquire_input_focus")

end

function fixed_update(self, dt)
	
end

function on_message(self, message_id, message, sender)
	
end

function on_input(self, action_id, action)
	input_remote_tv.on_input_core(self, action_id, action)
end

function on_reload(self)
	
end
